"""Add sitemap refresh progress

Revision ID: 2316699081a0
Revises: 8a063e7fa036
Create Date: 2026-02-21 14:45:55.102716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2316699081a0"
down_revision: Union[str, Sequence[str], None] = "8a063e7fa036"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sitemap_refresh_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sitemap_id", sa.Uuid(), nullable=False),
        sa.Column("website_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("urls_found", sa.Integer(), nullable=False),
        sa.Column("urls_new", sa.Integer(), nullable=False),
        sa.Column("urls_modified", sa.Integer(), nullable=False),
        sa.Column("errors", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(["sitemap_id"], ["sitemaps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sitemap_id", name="uq_sitemap_refresh_progress_sitemap_id"
        ),
    )
    with op.batch_alter_table("sitemap_refresh_progress", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sitemap_refresh_progress_updated_at", ["updated_at"], unique=False
        )
        batch_op.create_index(
            "ix_sitemap_refresh_progress_website_status",
            ["website_id", "status"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sitemap_refresh_progress", schema=None) as batch_op:
        batch_op.drop_index("ix_sitemap_refresh_progress_website_status")
        batch_op.drop_index("ix_sitemap_refresh_progress_updated_at")

    op.drop_table("sitemap_refresh_progress")
    # ### end Alembic commands ###
