"""Add activity logs

Revision ID: 3b991fb4d16c
Revises: 2316699081a0
Create Date: 2026-02-21 14:46:12.172145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b991fb4d16c"
down_revision: Union[str, Sequence[str], None] = "2316699081a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("website_id", sa.Uuid(), nullable=True),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.String(length=512), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_activity_logs_created_at", ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_activity_logs_event_type", ["event_type"], unique=False
        )
        batch_op.create_index(
            "ix_activity_logs_website_created_at",
            ["website_id", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_activity_logs_website_created_at")
        batch_op.drop_index("ix_activity_logs_event_type")
        batch_op.drop_index("ix_activity_logs_created_at")

    op.drop_table("activity_logs")
    # ### end Alembic commands ###
