"""Add quota discovery fields to website

Revision ID: 8a063e7fa036
Revises: be315f2f97af
Create Date: 2026-02-21 14:31:52.290151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a063e7fa036"
down_revision: Union[str, Sequence[str], None] = "be315f2f97af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("websites", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("discovered_indexing_quota", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("discovered_inspection_quota", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "quota_discovery_status",
                sa.Enum(
                    "pending",
                    "discovering",
                    "estimated",
                    "confirmed",
                    "failed",
                    name="quota_discovery_status",
                ),
                server_default="pending",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "quota_discovery_confidence",
                sa.Float(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("quota_discovered_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("quota_last_429_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("websites", schema=None) as batch_op:
        batch_op.drop_column("quota_last_429_at")
        batch_op.drop_column("quota_discovered_at")
        batch_op.drop_column("quota_discovery_confidence")
        batch_op.drop_column("quota_discovery_status")
        batch_op.drop_column("discovered_inspection_quota")
        batch_op.drop_column("discovered_indexing_quota")

    # ### end Alembic commands ###
