"""Initial schema

Revision ID: 992baa435c67
Revises: 
Create Date: 2026-02-21 14:09:01.620017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992baa435c67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('site_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_bucket_size', sa.Integer(), server_default=sa.text('(10)'), nullable=False),
    sa.Column('rate_limit_refill_rate', sa.Float(), server_default=sa.text('(1.0)'), nullable=False),
    sa.Column('rate_limit_max_concurrent_requests', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('rate_limit_queue_excess_requests', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_websites_domain'), ['domain'], unique=True)

    op.create_table('quota_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('indexing_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inspection_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'date', name='uq_quota_usages_website_id_date')
    )
    with op.batch_alter_table('quota_usages', schema=None) as batch_op:
        batch_op.create_index('ix_quota_usages_website_id_date', ['website_id', 'date'], unique=False)

    op.create_table('rate_limit_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('token_count', sa.Float(), nullable=False),
    sa.Column('last_refill_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', name='uq_rate_limit_states_website_id')
    )
    with op.batch_alter_table('rate_limit_states', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_states_website_id', ['website_id'], unique=False)

    op.create_table('service_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credentials_path', sa.String(length=1024), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_accounts_website_id'), ['website_id'], unique=True)

    op.create_table('sitemaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('sitemap_type', sa.Enum('INDEX', 'URLSET', name='sitemap_type'), nullable=False),
    sa.Column('last_fetched', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified_header', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'url', name='uq_sitemaps_website_id_url')
    )
    with op.batch_alter_table('sitemaps', schema=None) as batch_op:
        batch_op.create_index('ix_sitemaps_website_id', ['website_id'], unique=False)

    op.create_table('urls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('sitemap_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('lastmod', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changefreq', sa.String(length=32), nullable=True),
    sa.Column('sitemap_priority', sa.Float(), nullable=True),
    sa.Column('current_priority', sa.Float(), server_default=sa.text('(0.5)'), nullable=False),
    sa.Column('manual_priority_override', sa.Float(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('current_priority >= 0 AND current_priority <= 1', name='ck_urls_current_priority_range'),
    sa.CheckConstraint('manual_priority_override IS NULL OR (manual_priority_override >= 0 AND manual_priority_override <= 1)', name='ck_urls_manual_priority_override_range'),
    sa.CheckConstraint('sitemap_priority IS NULL OR (sitemap_priority >= 0 AND sitemap_priority <= 1)', name='ck_urls_sitemap_priority_range'),
    sa.ForeignKeyConstraint(['sitemap_id'], ['sitemaps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'url', name='uq_urls_website_id_url')
    )
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.create_index('ix_urls_current_priority', ['current_priority'], unique=False)
        batch_op.create_index('ix_urls_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_urls_website_id', ['website_id'], unique=False)

    op.create_table('index_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url_id', sa.Uuid(), nullable=False),
    sa.Column('coverage_state', sa.String(length=255), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'FAIL', 'NEUTRAL', 'PARTIAL', name='index_verdict'), nullable=False),
    sa.Column('last_crawl_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('robots_txt_state', sa.String(length=255), nullable=True),
    sa.Column('indexing_state', sa.String(length=255), nullable=True),
    sa.Column('page_fetch_state', sa.String(length=255), nullable=True),
    sa.Column('google_canonical', sa.String(length=2048), nullable=True),
    sa.Column('user_canonical', sa.String(length=2048), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('index_statuses', schema=None) as batch_op:
        batch_op.create_index('ix_index_statuses_url_id_checked_at', ['url_id', 'checked_at'], unique=False)

    op.create_table('submission_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('URL_UPDATED', 'URL_DELETED', name='submission_action'), nullable=False),
    sa.Column('api_response', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'RATE_LIMITED', 'SKIPPED', name='submission_status'), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_logs', schema=None) as batch_op:
        batch_op.create_index('ix_submission_logs_status', ['status'], unique=False)
        batch_op.create_index('ix_submission_logs_url_id_submitted_at', ['url_id', 'submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_logs_url_id_submitted_at')
        batch_op.drop_index('ix_submission_logs_status')

    op.drop_table('submission_logs')
    with op.batch_alter_table('index_statuses', schema=None) as batch_op:
        batch_op.drop_index('ix_index_statuses_url_id_checked_at')

    op.drop_table('index_statuses')
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index('ix_urls_website_id')
        batch_op.drop_index('ix_urls_updated_at')
        batch_op.drop_index('ix_urls_current_priority')

    op.drop_table('urls')
    with op.batch_alter_table('sitemaps', schema=None) as batch_op:
        batch_op.drop_index('ix_sitemaps_website_id')

    op.drop_table('sitemaps')
    with op.batch_alter_table('service_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_accounts_website_id'))

    op.drop_table('service_accounts')
    with op.batch_alter_table('rate_limit_states', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_states_website_id')

    op.drop_table('rate_limit_states')
    with op.batch_alter_table('quota_usages', schema=None) as batch_op:
        batch_op.drop_index('ix_quota_usages_website_id_date')

    op.drop_table('quota_usages')
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_websites_domain'))

    op.drop_table('websites')
    # ### end Alembic commands ###
