"""Add job_executions and url index status

Revision ID: be315f2f97af
Revises: 992baa435c67
Create Date: 2026-02-21 14:10:21.017417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be315f2f97af'
down_revision: Union[str, Sequence[str], None] = '992baa435c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('website_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('urls_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('checkpoint_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.create_index('ix_job_executions_job_id_started_at', ['job_id', 'started_at'], unique=False)
        batch_op.create_index('ix_job_executions_website_id_status', ['website_id', 'status'], unique=False)

    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_index_status', sa.Enum('INDEXED', 'NOT_INDEXED', 'BLOCKED', 'SOFT_404', 'ERROR', 'UNCHECKED', name='url_index_status'), server_default='UNCHECKED', nullable=False))
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_urls_website_id_latest_index_status', ['website_id', 'latest_index_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index('ix_urls_website_id_latest_index_status')
        batch_op.drop_column('last_checked_at')
        batch_op.drop_column('latest_index_status')

    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_job_executions_website_id_status')
        batch_op.drop_index('ix_job_executions_job_id_started_at')

    op.drop_table('job_executions')
    # ### end Alembic commands ###
